"""OOF / Relabel manifest loader with fail-closed validation.

Loads manifests generated by B (OOF quality scores, relabel decisions) and
validates schema, coverage, label consistency, and weight ranges before
training can proceed.
"""

from __future__ import annotations

import hashlib
import logging
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd
import numpy as np

logger = logging.getLogger(__name__)


def canonical_image_path(value: str) -> str:
    """Return a stable absolute key for an image path.

    Expands user home, resolves symlinks and relative components,
    and returns a str suitable as a dict key across providers.
    """
    return str(Path(value).expanduser().resolve())


def portable_image_key(value: str) -> str:
    """Return a machine-independent key: ``class_dir/filename``.

    Extracts the last two path components — the class directory and the
    image filename — which are invariant across machines, base-directory
    conventions (``train/`` vs ``train_dedup/``), and absolute-path
    prefixes.

    Raises:
        ValueError: If the path has fewer than two components.
    """
    p = Path(value)
    parts = p.parts
    if len(parts) < 2:
        raise ValueError(
            f"Path has fewer than two components; cannot extract "
            f"class_dir/filename from: {value!r}"
        )
    # Last two components are always class_dir/filename
    return str(Path(parts[-2]) / parts[-1])


REQUIRED_COLUMNS = [
    "sample_id",
    "image_path",
    "original_label",
    "training_label",
    "sample_weight",
    "quality_score",
]

OPTIONAL_COLUMNS = [
    "source",
    "oof_top1",
    "p_original_label",
    "p_top1",
    "prototype_margin",
    "knn_agreement",
    "flip_consistency",
    "training_role",
    "selection_reason",
    "suggested_label",
    "prototype_top1",
    "knn_top1",
    "top1_margin",
    "duplicate_conflict_flag",
]


class ManifestValidationError(ValueError):
    """Raised when a manifest fails validation."""


def _sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(1 << 20)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


class ManifestLoader:
    """Load and validate OOF/relabel manifests with fail-closed semantics.

    Usage::

        loader = ManifestLoader("outputs/phase3/oof/soft_weight_manifest.csv")
        df = loader.load()
        audit = loader.audit(df, dataset_labels)
        if audit["errors"]:
            raise ManifestValidationError(audit["errors"])
    """

    def __init__(self, manifest_path: str):
        self.path = Path(manifest_path)
        if not self.path.exists():
            raise FileNotFoundError(f"Manifest not found: {manifest_path}")
        self._sha256: Optional[str] = None

    @property
    def sha256(self) -> str:
        if self._sha256 is None:
            self._sha256 = _sha256(str(self.path))
        return self._sha256

    def load(self) -> pd.DataFrame:
        """Load manifest CSV and validate required columns.

        Returns:
            DataFrame with all manifest columns.

        Raises:
            ManifestValidationError: If required columns are missing.
        """
        df = pd.read_csv(self.path)
        missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
        if missing:
            raise ManifestValidationError(
                f"Manifest {self.path} is missing required columns: {missing}"
            )

        # Check for duplicate sample_ids
        dups = df["sample_id"].duplicated()
        if dups.any():
            dup_ids = df.loc[dups, "sample_id"].tolist()[:10]
            raise ManifestValidationError(
                f"Manifest contains duplicate sample_ids: {dup_ids}"
            )

        logger.info(
            "Manifest loaded: %d samples, %d columns, sha256=%s",
            len(df), len(df.columns), self.sha256[:16],
        )
        return df

    def audit(
        self,
        df: pd.DataFrame,
        dataset_labels: Dict[str, int],
        max_relabel_pct_per_class: float = 5.0,
        max_relabel_pct_global: float = 3.0,
    ) -> dict:
        """Audit manifest against ground-truth dataset labels.

        Args:
            df: Loaded manifest DataFrame.
            dataset_labels: Dict mapping image_path → label from the dataset.
            max_relabel_pct_per_class: Max % of samples per class that may be
                relabeled (default 5%).
            max_relabel_pct_global: Max % of all samples that may be relabeled
                (default 3%).

        Returns:
            Dict with keys: errors (list[str]), warnings (list[str]),
            coverage (float), per_class_relabel_pct (dict).
        """
        errors: List[str] = []
        warnings: List[str] = []

        n_manifest = len(df)
        n_dataset = len(dataset_labels)

        # Coverage
        manifest_paths = set(df["image_path"].tolist())
        dataset_paths = set(dataset_labels.keys())
        missing_in_manifest = dataset_paths - manifest_paths
        extra_in_manifest = manifest_paths - dataset_paths

        if missing_in_manifest:
            errors.append(
                f"Manifest missing {len(missing_in_manifest)} samples "
                f"present in dataset"
            )
        if extra_in_manifest:
            errors.append(
                f"Manifest contains {len(extra_in_manifest)} samples "
                f"not in dataset"
            )

        coverage = (
            len(manifest_paths & dataset_paths) / n_dataset
            if n_dataset > 0
            else 0.0
        )
        if coverage < 1.0:
            errors.append(
                f"Manifest coverage is {coverage:.2%} (must be 100%)"
            )

        # Label consistency
        label_mismatches = 0
        for _, row in df.iterrows():
            path = row["image_path"]
            if path in dataset_labels:
                expected = int(dataset_labels[path])
                actual = int(row["original_label"])
                if expected != actual:
                    label_mismatches += 1
        if label_mismatches > 0:
            errors.append(
                f"{label_mismatches} samples have original_label != dataset label"
            )

        # Weight range
        w_min = float(df["sample_weight"].min())
        w_max = float(df["sample_weight"].max())
        if w_min < 0.0:
            errors.append(f"sample_weight min is {w_min} (< 0)")
        if w_max > 1.0:
            errors.append(f"sample_weight max is {w_max} (> 1)")

        # Relabel rate
        relabeled = df["original_label"] != df["training_label"]
        n_relabeled = int(relabeled.sum())
        global_pct = 100.0 * n_relabeled / n_manifest if n_manifest > 0 else 0.0

        if global_pct > max_relabel_pct_global:
            errors.append(
                f"Global relabel rate {global_pct:.1f}% exceeds "
                f"maximum {max_relabel_pct_global}%"
            )

        per_class_pct = {}
        if n_relabeled > 0:
            for c in df["original_label"].unique():
                c_mask = df["original_label"] == c
                c_total = int(c_mask.sum())
                c_relabeled = int((c_mask & relabeled).sum())
                c_pct = 100.0 * c_relabeled / c_total if c_total > 0 else 0.0
                per_class_pct[str(c)] = c_pct
                if c_pct > max_relabel_pct_per_class:
                    errors.append(
                        f"Class {c}: relabel rate {c_pct:.1f}% exceeds "
                        f"maximum {max_relabel_pct_per_class}%"
                    )

        return {
            "errors": errors,
            "warnings": warnings,
            "coverage": coverage,
            "n_total": n_manifest,
            "n_relabeled": n_relabeled,
            "global_relabel_pct": global_pct,
            "weight_min": w_min,
            "weight_max": w_max,
            "weight_mean": float(df["sample_weight"].mean()),
            "per_class_relabel_pct": per_class_pct,
            "manifest_sha256": self.sha256,
        }
